### ISSUE TITLE
Tune.py: growing cpu usage under Linux

### ISSUE THREAD

**Issue by joergoster** [thomasahle/fastchess#10]
As already mentioned, with increasing number of games I notice cpu usage keeps growing, as well, with peaks up to > 90%. Still investigating

**Comment by joergoster** [comment]
Running `top` alongside the tuning process, it looks like the python3 process is demanding more and more cpu power with increasing number of games. I also noticed a very oscillating cpu usage.

@thomasahle Is it possible that the computational effort keeps growing with time, especially with a higher number of parameters to be tuned?

**Comment by joergoster** [comment]
@thomasahle See https://stackoverflow.com/questions/10427900/stop-python-from-using-more-than-one-cpu for example.

Running the script with `OMP_NUM_THREADS=1 python3 tune.py ...` solves this issue for me! Now the python3 process is never using more than 100% !

**Comment by thomasahle** [comment]
@joergoster But doesn't it just take longer to complete then?
I've pushed a new update which hopefully helps on the memory issue. Do you mind giving it a spin?

**Comment by joergoster** [comment]
@thomasahle Already up and running. ;-)

**Comment by joergoster** [comment]
@thomasahle Sure it takes longer, but these days cooling is the problem. And I don't want to hog-up all cpu power only for the tuning tests. Currently I'm running with OMP_NUM_THREADS=2 or OMP_NUM_THREADS=3.

Tried your updated version and the increasing memory consumption seems to be gone. Great!

Now I'm getting an errror message when it comes to summarizing the best values. Not sure it's the script or it's on my side. Just noticed your latest commit, so will try again tomorrow.

**Comment by thomasahle** [comment]
Otherwise send me the error message

**Comment by joergoster** [comment]
@thomasahle The error occured because of the parallel installation of Python3.6 and 3.7 and a recent system upgrade. Funnyhow, the error didn't show up when using 'GBRT' as the base estimator.

Below are 2 examples, one with RF, the other with GBRT (only 100 iterations each). Using RF, the best values are followed by a period. Funny!

base estimator = RF
```
Summarizing best values
Best expectation (κ=0): [ 0. 47.  4. 85. 14. 14. 74. 47. 22. 76.] = 0.504 ± 0.486 (ELO-diff 192.717 ± 723.541)
Best expectation (κ=1): [ 0. 47.  4. 85. 14. 14. 74. 47. 22. 76.] = 0.504 ± 0.486 (ELO-diff 192.717 ± 723.541)
Best expectation (κ=2): [ 3. 44. 23. 84. 17. 27. 78.  4. 56. 76.] = 0.389 ± 0.396 (ELO-diff 142.804 ± 225.442)
Best expectation (κ=3): [ 3. 44. 23. 84. 17. 27. 78.  4. 56. 76.] = 0.389 ± 0.396 (ELO-diff 142.804 ± 225.442)
```

base estimator = GBRT
```
Summarizing best values
Best expectation (κ=0): [ 9 47 51 18 22 37 70 62 13  3] = -0.000 ± 0.511 (ELO-diff -0.000 ± 195.793)
Best expectation (κ=1): [ 3 26 86 27 28  9 68 79 53 76] = -0.000 ± 0.168 (ELO-diff -0.000 ± 58.750)
Best expectation (κ=2): [ 3 26 86 27 28  9 68 79 53 76] = -0.000 ± 0.168 (ELO-diff -0.000 ± 58.750)
Best expectation (κ=3): [ 3 26 86 27 28  9 68 79 53 76] = -0.000 ± 0.168 (ELO-diff -0.000 ± 58.750)

```

**Comment by thomasahle** [comment]
Haha, I can't say why one uses float and the other one not. Perhaps skopt should round them to make things more similar.
Do you know why the values in the two cases are so different?

In either case, I'm closing this bug. We no longer have a memory leak, and that GP uses a lot of cpu is probably not something we can fix. Skopt will have to do that, if at all possible.
One thing we might do is to default to RF or GBRT, at least for n > 500. Let me know if you have an oppionon on that.

**Comment by joergoster** [comment]
I would vote for GBRT as default, but that's just a guess.

Values are so different because with only 100 iterations is just like rolling a dice.
Evaluation parameters are tuned with something like 20,000 to 50,000 games _at minimum_.

**Comment by thomasahle** [comment]
Sure, you probably need exponentially many in the number of parameters.
Ive noticed though that GP often does a bit too little exploration. For that I've added the noise argument. For me it finds the right values (with 2 parameters) much faster when setting the noise to around 10.

If you end up doing 20k iterations with both GBRT and RT it would be interesting to hear which converges faster.

**Comment by thomasahle** [comment]
It is also possible that other baysian optimization packages are faster. E.g. hyperopt or GPyOpt. see
https://github.com/scikit-optimize/scikit-optimize/issues/334 for how skopt doesn't really care about `ask` performance.

Another library that's meant to be much fastre is simple(x): https://github.com/chrisstroemel/Simple

https://medium.com/georgian-impact-blog/automatic-machine-learning-aml-landscape-survey-f75c3ae3bbf2 has a long list of different options.

**Comment by joergoster** [comment]
Unfortunately, I'm getting an error again. It's the same that I got yesterday and which I thought I had solved. Still not sure if it's related to my system or to the script.

Here it is:

> Summarizing best values
> /usr/lib/python3.7/asyncio/unix_events.py:861: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
>   RuntimeWarning)
> Traceback (most recent call last):
>   File "tune.py", line 483, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "tune.py", line 463, in main
>     summarize(opt, samples=args.n)
>   File "tune.py", line 334, in summarize
>     pm = max(abs(score_to_elo(y_pred[i] / 2 + sigma[i] / 2) - elo),
>   File "tune.py", line 332, in score_to_elo
>     return - 400 * math.log10(2 / (score + 1) - 1)
> ValueError: math domain error
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
>     from apport.fileutils import likely_packaged, get_recent_crashes
>   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
>     from apport.report import Report
>   File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
>     import apport.fileutils
>   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
>     from apport.packaging_impl import impl as packaging
>   File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
>     import apt
>   File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
>     import apt_pkg
> ModuleNotFoundError: No module named 'apt_pkg'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "tune.py", line 483, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "tune.py", line 463, in main
>     summarize(opt, samples=args.n)
>   File "tune.py", line 334, in summarize
>     pm = max(abs(score_to_elo(y_pred[i] / 2 + sigma[i] / 2) - elo),
>   File "tune.py", line 332, in score_to_elo
>     return - 400 * math.log10(2 / (score + 1) - 1)
> ValueError: math domain error

P.S. Thank you for the links.

**Comment by thomasahle** [comment]
@joergoster can you open a new issue about that?
It looks like score is 1 and thus explodes the log.
I wouldn't think this could happen, but maybe if you are using something other than GP?
