### ISSUE TITLE
tune.py: Remove exclusiveness of max-len from movetime and nodes

### ISSUE THREAD

**Issue by fsmosca** [thomasahle/fastchess#14]
#### Suggestion
Game length in plies has nothing to do with move controls like movetime and nodes.
`-movetime 50 -max-len 200` 
can be a reasonable setup for the user.

**Comment by thomasahle** [comment]
I'm not sure I understand this one.

**Comment by fsmosca** [comment]
Currently `-movetime 50 -max-len 200` does not work, because movetime and max-len are mutually exclusive.

Better is,
```
parser.add_argument(
    '-max-len',
    type=int,
    default=10000,
    help='Maximum length of game in plies before termination.')
```

**Comment by thomasahle** [comment]
Ah, I see. It should have been on the group rather than the subgroup. Do you want to make a pull request? You seem to have a lot of good suggestions and that way we can get them integrated much faster.

**Comment by fsmosca** [comment]
Yes it could be in another group but not on mutually exclusive group.

Perhaps next time will try to make a PR.

I am actually trying to add game adjudication by score.

**Comment by thomasahle** [comment]
Adjudication by score would be nice :-)

**Comment by fsmosca** [comment]
Created a fork and implemented the win adjudication.
https://github.com/fsmosca/fastchess/commit/271d9fcce5dc90e810ed4052238c8e6b9a2cf593

I have tested it on a couple of games and it seemed to work. I will do more tests before submitting a  PR.
