### ISSUE TITLE
can't isntall pip install git+https://github.com/facebookresearch/fastText.git from cmd in windows help plz

### ISSUE THREAD

**Issue by vedant8top** [thomasahle/fastchess#28]
pip install git+https://github.com/facebookresearch/fastText.git
it is not working in cmd  in windows
Collecting git+https://github.com/facebookresearch/fastText.git
  Cloning https://github.com/facebookresearch/fastText.git to c:\users\vedant\appdata\local\temp\pip-req-build-_draur5m
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/facebookresearch/fastText.git 'C:\Users\Vedant\AppData\Local\Temp\pip-req-build-_draur5m'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by thomasahle** [comment]
Sounds like you don't have git installed?

**Comment by vedant8top** [comment]
Thanks
