### ISSUE TITLE
Python3.7 for running tune.py is mandatory?

### ISSUE THREAD

**Issue by joergoster** [thomasahle/fastchess#7]
On my Linux system, current python3 version is 3.6.8. This gives me following error message when trying to run tune.py.
```
  File "tune.py", line 368, in <module>
    asyncio.run(main())
AttributeError: module 'asyncio' has no attribute 'run'
```
Is there a workaround?

P.S. Support of different kind of time controls and fixed depth would be great, too!

**Comment by thomasahle** [comment]
Ah, that's true. In python 3.6 one would use `loop.run_until_complete(future) ` which does roughly the same thing.

Fixed depth and time controls shouldn't be too hard. I'll be happy to take pull requests, but otherwise it may take a little while to get done.

**Comment by joergoster** [comment]
I managed to install Python 3.7 in parallel to 3.6, and I can choose which version to be used as python3.
So closing this one.

**Comment by thomasahle** [comment]
@joergoster I've pushed a version with the `rrun_until_complete` call. If you still have python 3.6, do you want to check if it works now?

**Comment by joergoster** [comment]
@thomasahle Unfortunately, this version doesn't work under Python 3.6.8.

```
python3 -V
Python 3.6.8
```

> 
> python3 tune.py Stockfish -nodes 800 -concurrency=2 -book ../openings/feobos_v20.1-contempt-3.pgn -games-file tune.pgn -opt mBackward -opt eBackward -opt mDoubled -opt eDoubled -opt mIsolated -opt eIsolated -opt mRookOnFile[0] -opt eRookOnFile[0] -opt mRookOnFile[1] -opt eRookOnFile[1] -n 20 -log-file data.log
> /home/joster/.local/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
>   warnings.warn(msg, category=DeprecationWarning)
> Loaded book with 33010 positions
> Loading engines
> Parsing options
> Reading data.log
> Starting game 1/20 with {'mBackward': 258, 'eBackward': 83, 'mDoubled': 293, 'eDoubled': 351, 'mIsolated': 203, 'eIsolated': 364, 'mRookOnFile[0]': 90, 'eRookOnFile[0]': 136, 'mRookOnFile[1]': 82, 'eRookOnFile[1]': 239}
> Traceback (most recent call last):
>   File "tune.py", line 433, in <module>
>     asyncio.get_event_loop().run_until_complete(main())
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
>     return future.result()
>   File "tune.py", line 388, in main
>     async for games, x, y, er in run(opt, engines, book, limit, args.max_len, dim_names, args.concurrency, args.n - cached_games, options):
>   File "tune.py", line 283, in run
>     start_new(conc_id, x_init)
>   File "tune.py", line 254, in start_new
>     task = asyncio.create_task(get_value(
> AttributeError: module 'asyncio' has no attribute 'create_task'

**Comment by joergoster** [comment]
@thomasahle It would be great if you could solve this because it looks like many system services depend on Python 3.6.

**Comment by thomasahle** [comment]
You can try replacing `asyncio.create_task(` with `asyncio.get_event_loop().create_task(`.
